[language-server.clangd]
command = "clangd"
args = ["--header-insertion=never", "--completion-style=detailed"]

[language-server.tailwindcss-lsp]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server.typescript-language-server]
config.preferences.importModuleSpecifierPreference = "non-relative"

[use-grammars]
only = [
  "c", "cpp", "d", "rust", "zig", "go", "ocaml", "haskell",
  "javascript", "typescript", "html", "css", "jsx", "tsx",
  "python", "lua", "bash",
  "json", "toml", "yaml", "make", "cmake"
]

[[language]]
name = "c"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "cpp"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "ocaml"
formatter = { command = "ocamlformat", args = [
  "-",
  "--impl",
  "--enable-outside-detected-project",
]}

[[language]]
name = "haskell"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "python"
language-servers = ["pyright"]

[[language]]
name = "jsx"
block-comment-tokens = { start = "{/*", end = "*/}" }
language-servers = ["typescript-language-server", "tailwindcss-lsp"]

[[language]]
name = "tsx"
block-comment-tokens = { start = "{/*", end = "*/}" }
language-servers = ["typescript-language-server", "tailwindcss-lsp"]

